<!--Reviews.co.uk Rich Widget - Includes Company Rich Snippets-->
<link rel="stylesheet" type="text/css" defer href="https://widget.reviews.co.uk/floating-widget/css/dist.css">
<script src="https://widget.reviews.co.uk/rich-snippet-reviews-widgets/dist.js" defer type="text/javascript"></script>
<script>
    window.onload = function() {
        richSnippetReviewsWidgets({
            store: "silver-bubble",
            primaryClr: "#009985",
            widgetName: "floating-widget",
            numReviews: 40,
            floatPosition: "right",
            contentMode: "company",
            hideDates: true
        });
    };
</script>
